config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => 'lists#index'

  resources :lists do
    resources :tasks, :except => [:show, :index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :tasks, dependent: :destroy
  validates :name, :presence => true
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :list

  validates :description, :presence => true

  scope(:done, -> do
    where({:done => true})
  end)

  scope(:not_done, -> do
    where({:done => false})
  end)

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   attr_accessor :login

   def self.find_for_database_authentication(warden_conditions)
     conditions = warden_conditions.dup
     if login = conditions.delete(:login)
       where(conditions.to_hash).where(["username = :value OR email = :value", { :value => login.downcase }]).first
     elsif conditions.has_key?(:username) || conditions.has_key?(:email)
       where(conditions.to_hash).first
     end
   end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username, :email])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email])
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      flash[:notice] = "List successfully added!"
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list= List.find(params[:id])
    if @list.update(list_params)
      redirect_to lists_path
    else
      render :edit
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end

private
  def list_params
    params.require(:list).permit(:name)
  end


end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!

  def new
    @list = List.find(params[:list_id])
    @task = @list.tasks.new
  end

  def create
    @list = List.find(params[:list_id])
    @task = @list.tasks.new(task_params)
    if @task.save
      respond_to do |format|
        format.html { redirect_to list_path(@list) }
        format.js
      end
    else
      render :new
    end
  end

  def edit
    @list = List.find(params[:list_id])
    @task = Task.find(params[:id])
  end

  def update
    @list = List.find(params[:list_id])
    @task = Task.find(params[:id])
    if @task.update(task_params)
      respond_to do |format|
        format.html { redirect_to list_path(@list) }
        format.js
      end
    else
      render :edit
    end
  end

  def destroy
    @list = List.find(params[:list_id])
    @task = Task.find(params[:id])
    @task.destroy
    respond_to do |format|
      format.html { redirect_to list_path(@list) }
      format.js
    end
  end

private
  def task_params
    params.require(:task).permit(:description, :done)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <% if user_signed_in? %>
    Logged in as <strong><%= current_user.email %></strong>
    <%= link_to "Edit profile", edit_user_registration_path %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> |
    <%= link_to "Login", new_user_session_path %>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= render 'layouts/flash' %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/lists/_form.html.erb
<%= render "layouts/errors", :object => @list %>

<%= form_for @list do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/lists/edit.html.erb
<h1>Edit list</h1>

<%= render "form" %>

app/views/lists/index.html.erb
<h1>Lists</h1>

<ul>
  <% @lists.each do |list| %>
    <li><%= link_to list.name, list_path(list) %></li>
  <% end %>
</ul>

<hr>

<%= link_to "New List", new_list_path %>

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render "form" %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>

<div id="task_lists">
  
  <div id="unfinished-tasks" class="<%= 'hidden' if !@list.tasks.not_done.any? %>">
    <h4>Here are the <em>unfinished</em> tasks for this list:</h4>
    <ul>
      <%= render @list.tasks.not_done %>
    </ul>
  </div>

  <div id="finished-tasks" class="<%= 'hidden' if !@list.tasks.done.any? %>">
    <h4>Here are the <em>finished</em> tasks for this list:</h4>
    <ul>
      <%= render @list.tasks.done %>
    </ul>
  </div>

  <div id="no-tasks" class="<%= 'hidden' if @list.tasks.any? %>">
    <p id="no-tasks-label">There are no tasks yet!</p>
  </div>

</div>

<p><%= link_to "Add a task", new_list_task_path(@list), id: "new_task_link", class: "btn btn-default", remote: true %></p>
<p><%= link_to "Delete List", list_path(@list),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Return to lists", lists_path %></p>

app/views/tasks/_form.html.erb
<%= render('layouts/errors', :object => @task) %>

<%= form_for [@list, @task], remote: true do |f| %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <p><%= f.submit %></p>
<% end %>

app/views/tasks/_task.html.erb
<li id="task_<%= task.id %>" class="task input-group">
  <%= task.description %> |
  <%= link_to "Edit", edit_list_task_path(@list, task) %> |
  <%= link_to "Delete", list_task_path(@list, task), remote: true, 
                           :data => {:confirm => "Are you sure?",
                                          :method => "delete"} %> |
  <%= form_for [@list, task], remote: true do |f| %>
    <%= f.hidden_field :done, :value => !task.done %>
    <% if !task.done %>
      <%= f.submit "mark done", class: 'btn btn-link' %>
    <% else %>
      <%= f.submit "not done", class: 'btn btn-link' %>
    <% end %>
  <% end %>
</li>

app/views/tasks/create.js.erb
$('form#new_task').remove();
$('#new_task_link').show();
$('#no-tasks').addClass('hidden');
$('#unfinished-tasks').removeClass('hidden');
$('#unfinished-tasks ul').append('<%= j render(@task) %>')

app/views/tasks/destroy.js.erb
$("#task_<%= @task.id %>").remove();
<%= @list.tasks.done.any? %> ? $('#finished-tasks').removeClass('hidden') : $('#finished-tasks').addClass('hidden');
<%= @list.tasks.not_done.any? %> ? $('#unfinished-tasks').removeClass('hidden') : $('#unfinished-tasks').addClass('hidden');
if(<%= !@list.tasks.any? %>) {
 $('#no-tasks').removeClass('hidden');
}

app/views/tasks/edit.html.erb
<h1>Edit task</h1>

<%= render "form" %>

app/views/tasks/new.html.erb
<h1>New task for <%= @list.name %></h1>

<%= render 'form' %>

app/views/tasks/new.js.erb
$('#new_task_link').hide().after('<%= j render("form") %>')

app/views/tasks/update.js.erb
$("#task_<%= @task.id %>").remove();
<%= @list.tasks.done.any? %> ? $('#finished-tasks').removeClass('hidden') : $('#finished-tasks').addClass('hidden');
<%= @list.tasks.not_done.any? %> ? $('#unfinished-tasks').removeClass('hidden') : $('#unfinished-tasks').addClass('hidden');
if(<%= @task.done %>) {
  $('#finished-tasks ul').append("<%= j render @task %>");
} else {
  $('#unfinished-tasks ul').append("<%= j render @task %>");
}

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>